development:
  adapter: postgresql
  encoding: unicode
  database: week_9_assessment_development
  pool: 5
  username: gschool
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: week_9_assessment_test
  pool: 5
  username: gschool
  password:
